[package]
name = "micro-llm"
version = "0.1.0"
edition = "2024"
license = "MIT"

[workspace]
members = [
    "crates/*"
]

[dependencies]


[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
