[package]
name = "micro_tokenizer"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = { version = "1.0.142", optional = true }
anyhow = { version = "1.0.80", optional = true }

[features]
default = []
hf = ["dep:serde_json", "dep:anyhow"]