[package]
name = "micro_executor"
version = "0.1.0"
edition = "2024"

[dependencies]
safetensors = "0.6.1"
memmap2 = "0.9.7"
half = { version = "2.6.0", features = ["bytemuck"] }
ndarray = "0.16.1"
bytemuck = "1.23.1"
anyhow = "1.0.98"
thiserror = "2.0.12"
num-traits = "0.2.19"
